### - Get Tester
GET http://localhost:7071/api/get-tester-http-trigger?email=ardepena@gmail.com
Content-Type: application/json

### - Get Test Link
GET http://localhost:7071/api/get-test-link-http-trigger?email=maganj@demo.com
Content-Type: application/json

### - Post Tester
POST http://localhost:7071/api/save-tester-http-trigger
Content-Type: application/json

{
    "firstName": "Alberto",
    "lastName": "De Pena",
    "email": "ardepena@gmail.com",
    "dob": "May/23/1989"
}

### - Generate Test Link
POST https://sync.cnsvs.com/sync.php
Content-Type: application/x-www-form-urlencoded

request=rtl
&account=
&username=
&password=
&subject_id=
&dob_year=1989
&dob_month=May
&dob_day=23
&test_config=9
&test_lang=english_us