### - Get Tester
GET http://localhost:7071/api/get-tester-http-trigger?email=maganj@demo.com
Content-Type: application/json

### - Get Test Link
GET http://localhost:7071/api/get-test-link-http-trigger?email=maganj@demo.com
Content-Type: application/json

### - Post Tester
POST http://localhost:7071/api/save-tester-http-trigger
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "Magan",
    "email": "maganj@demo.com",
    "dob": "Dec/02/1985"
}

### - Post Teste Results
POST http://localhost:7071/api/save-test-results-http-trigger
Content-Type: application/x-www-form-urlencoded

cnsvs_id=12345
&account_id=11224
&test_date=2019-05-06
&test_time=01:01:01
&timezone=cst
&gmt_test_date=2019-05-06
&gmt_test_time=01:01:01
&subject_id=maganj@demo.com
&birth_date=1985-12-02
&gender=male
&duration=5000
&language=english_us
&domain_data=<data><name>Composite Memory</name><valid>Yes</valid><raw>87</raw><ss>73</ss><pr>4</pr></data>